/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.mx.interfaces;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import uam.mx.clases.Boleto;
import uam.mx.clases.Cliente;
import uam.mx.clases.Función;
import uam.mx.clases.Película;
import uam.mx.clases.Usuario;
import uam.mx.clases.Venta;
import uam.mx.clases.VentaBoleto;

/**
 *
 * @author Laura
 */
public final class NuevaVentaBoletos extends javax.swing.JFrame {
    Función función;
    Cliente cliente;
    float total;
    Integer puntosAñadidos;
    Boolean f = false;
    ArrayList<Boleto> listaBoleto;
    /**
     * Creates new form NuevaVentaBoletos
     */
    public NuevaVentaBoletos() {
        initComponents();
        listaBoleto = new ArrayList<>();
        llenarFunciones();
        cmb_Asiento.removeAllItems();
        txt_NombreCliente.setEditable(false);
        txt_NombreCliente.setCaretColor(Color.white);
        llenarDescuento();
        llenarTipoPago();
    }
    
    public void llenarTipoPago() {
        cmb_TipoPago.removeAllItems();
        cmb_TipoPago.addItem("-Seleccionar-");
        cmb_TipoPago.addItem("Efectivo");
        cmb_TipoPago.addItem("Tarjeta");
    }
    
    private void llenarDescuento() {
        cmb_Descuento.removeAllItems();
        cmb_Descuento.addItem("-Seleccionar-");
        cmb_Descuento.addItem("Puntos");
        cmb_Descuento.addItem("No aplicar");
    }
    
    private void llenarFunciones() {
        cmb_Función.removeAllItems();
        cmb_Función.addItem("-Seleccionar-");
        ArrayList<Función> al = InicioSesión.cine.getCartelera().getListaFunciones();
        for(Función f : al) {
            String s = InicioSesión.cine.getCartelera().getListaPelículas().get(f.getId_película()).getNombre() + " | "
                        + "Sala " + f.getSala().getID() + " | " + f.getFecha() + " | " + f.getHorario() + " | " + InicioSesión.cine.getCartelera().formato(f.getFormato());
            cmb_Función.addItem(s);
        }
    }
    
    private void llenarAsientos() {
        cmb_Asiento.removeAllItems();
        int id = cmb_Función.getSelectedIndex() - 1;
        Función f = InicioSesión.cine.getCartelera().getListaFunciones().get(id);
        cmb_Asiento.addItem("-Seleccionar-");
        for(int i = 0; i < f.getSala().getAsientos().size(); ++i) {
            if(f.getSala().getAsientos().get(i).getOcupado() == false) {
                cmb_Asiento.addItem(f.getSala().getID() + "-" + f.getSala().getAsientos().get(i).getId());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_PagoTarjeta = new javax.swing.JDialog();
        jp_PagoTarjeta = new javax.swing.JPanel();
        lbl_PagoTarjeta = new javax.swing.JLabel();
        txt_NombreCompleto = new javax.swing.JTextField();
        lbl_TipoTarjeta = new javax.swing.JLabel();
        cmb_TipoTarjeta = new javax.swing.JComboBox<>();
        lbl_NumTarjeta = new javax.swing.JLabel();
        lbl_DatosTarjeta = new javax.swing.JLabel();
        lbl_NombreCompleto = new javax.swing.JLabel();
        txt_NumTarjeta = new javax.swing.JTextField();
        btn_Continuar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        dlg_MICHísimasGracias = new javax.swing.JDialog();
        jp_PagoTarjeta1 = new javax.swing.JPanel();
        lbl_PagoTarjeta1 = new javax.swing.JLabel();
        lbl_NumTarjeta1 = new javax.swing.JLabel();
        txt_Puntos = new javax.swing.JTextField();
        btn_Continuar1 = new javax.swing.JButton();
        lbl_Username = new javax.swing.JLabel();
        jp_Principal = new javax.swing.JPanel();
        btn_Regresar = new javax.swing.JButton();
        loguito = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_listaAsientosSeleccionados = new javax.swing.JLabel();
        cmb_Asiento = new javax.swing.JComboBox<>();
        jp_DatosFuncion = new javax.swing.JPanel();
        lbl_Portada = new javax.swing.JLabel();
        lbl_TituloPelicula = new javax.swing.JLabel();
        lbl_DescripcionPelicula = new javax.swing.JLabel();
        lbl_ClasificacionPelicula = new javax.swing.JLabel();
        lbl_SalaPelicula = new javax.swing.JLabel();
        lbl_DiaPelicula = new javax.swing.JLabel();
        lbl_FormatoPelicula = new javax.swing.JLabel();
        lbl_HoraPelicula = new javax.swing.JLabel();
        lbl_DuracionPelicula = new javax.swing.JLabel();
        lbl_CostoPelicula = new javax.swing.JLabel();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_NombreCliente = new javax.swing.JLabel();
        cmb_TipoPago = new javax.swing.JComboBox<>();
        lbl_Asiento = new javax.swing.JLabel();
        lbl_Cantidad = new javax.swing.JLabel();
        lbl_SeleccionarFuncion = new javax.swing.JLabel();
        txt_UsuarioCliente = new javax.swing.JTextField();
        lbl_UsuarioCliente = new javax.swing.JLabel();
        txt_NombreCliente = new javax.swing.JTextField();
        lbl_CambioPuntos = new javax.swing.JLabel();
        cmb_Función = new javax.swing.JComboBox<>();
        lbl_TotalT = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        lbl_TipoPago = new javax.swing.JLabel();
        cmb_Descuento = new javax.swing.JComboBox<>();
        lbl_Descuento = new javax.swing.JLabel();
        lbl_Variables = new javax.swing.JLabel();
        sp_Cantidad = new javax.swing.JSpinner();
        lbl_Subtotal = new javax.swing.JLabel();
        lbl_SubtotalT = new javax.swing.JLabel();
        btn_CompletarVenta = new javax.swing.JButton();
        btn_SeleccionarAsientos = new javax.swing.JButton();
        btn_SeleccionarAsientos1 = new javax.swing.JButton();
        lbl_Actuales = new javax.swing.JLabel();
        lbl_PuntosActuales = new javax.swing.JLabel();

        jp_PagoTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        jp_PagoTarjeta.setPreferredSize(new java.awt.Dimension(600, 400));

        lbl_PagoTarjeta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_PagoTarjeta.setText("PAGO CON TARJETA");

        txt_NombreCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NombreCompleto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_TipoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TipoTarjeta.setText("Tipo de tarjeta:");

        cmb_TipoTarjeta.setBackground(java.awt.SystemColor.control);
        cmb_TipoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_TipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_TipoTarjeta.setToolTipText("");
        cmb_TipoTarjeta.setBorder(null);

        lbl_NumTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NumTarjeta.setText("Número de la tarjeta:");

        lbl_DatosTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_DatosTarjeta.setText("Datos de la tarjeta:");

        lbl_NombreCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NombreCompleto.setText("Nombre completo:");

        txt_NumTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NumTarjeta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_Continuar.setBackground(new java.awt.Color(57, 105, 138));
        btn_Continuar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_Continuar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Continuar.setText("Continuar");
        btn_Continuar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Continuar.setBorderPainted(false);
        btn_Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ContinuarActionPerformed(evt);
            }
        });

        btn_Cancelar.setBackground(new java.awt.Color(102, 102, 102));
        btn_Cancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Cancelar.setBorderPainted(false);
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_PagoTarjetaLayout = new javax.swing.GroupLayout(jp_PagoTarjeta);
        jp_PagoTarjeta.setLayout(jp_PagoTarjetaLayout);
        jp_PagoTarjetaLayout.setHorizontalGroup(
            jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PagoTarjetaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_PagoTarjeta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                            .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_NumTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_NombreCompleto)
                                .addComponent(txt_NumTarjeta)))
                        .addComponent(lbl_DatosTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                            .addComponent(lbl_TipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(cmb_TipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jp_PagoTarjetaLayout.setVerticalGroup(
            jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbl_PagoTarjeta)
                .addGap(31, 31, 31)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TipoTarjeta)
                    .addComponent(cmb_TipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_DatosTarjeta)
                .addGap(18, 18, 18)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NombreCompleto))
                .addGap(18, 18, 18)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NumTarjeta)
                    .addComponent(txt_NumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlg_PagoTarjetaLayout = new javax.swing.GroupLayout(dlg_PagoTarjeta.getContentPane());
        dlg_PagoTarjeta.getContentPane().setLayout(dlg_PagoTarjetaLayout);
        dlg_PagoTarjetaLayout.setHorizontalGroup(
            dlg_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_PagoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlg_PagoTarjetaLayout.setVerticalGroup(
            dlg_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_PagoTarjetaLayout.createSequentialGroup()
                .addComponent(jp_PagoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        jp_PagoTarjeta1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_PagoTarjeta1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_PagoTarjeta1.setText("MICHÍsimas gracias por tu compra");

        lbl_NumTarjeta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NumTarjeta1.setText("Puntos actuales:");

        txt_Puntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_Puntos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_Continuar1.setBackground(new java.awt.Color(57, 105, 138));
        btn_Continuar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_Continuar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Continuar1.setText("Continuar");
        btn_Continuar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Continuar1.setBorderPainted(false);
        btn_Continuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Continuar1ActionPerformed(evt);
            }
        });

        lbl_Username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N

        javax.swing.GroupLayout jp_PagoTarjeta1Layout = new javax.swing.GroupLayout(jp_PagoTarjeta1);
        jp_PagoTarjeta1.setLayout(jp_PagoTarjeta1Layout);
        jp_PagoTarjeta1Layout.setHorizontalGroup(
            jp_PagoTarjeta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PagoTarjeta1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jp_PagoTarjeta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Continuar1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_PagoTarjeta1Layout.createSequentialGroup()
                        .addComponent(lbl_NumTarjeta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 69, Short.MAX_VALUE))
            .addGroup(jp_PagoTarjeta1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_PagoTarjeta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Username)
                    .addComponent(lbl_PagoTarjeta1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_PagoTarjeta1Layout.setVerticalGroup(
            jp_PagoTarjeta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PagoTarjeta1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbl_PagoTarjeta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Username)
                .addGap(19, 19, 19)
                .addGroup(jp_PagoTarjeta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Puntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NumTarjeta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Continuar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlg_MICHísimasGraciasLayout = new javax.swing.GroupLayout(dlg_MICHísimasGracias.getContentPane());
        dlg_MICHísimasGracias.getContentPane().setLayout(dlg_MICHísimasGraciasLayout);
        dlg_MICHísimasGraciasLayout.setHorizontalGroup(
            dlg_MICHísimasGraciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_PagoTarjeta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlg_MICHísimasGraciasLayout.setVerticalGroup(
            dlg_MICHísimasGraciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_PagoTarjeta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_Principal.setBackground(new java.awt.Color(255, 255, 255));

        btn_Regresar.setBackground(new java.awt.Color(102, 102, 102));
        btn_Regresar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_Regresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Regresar.setText("Regresar");
        btn_Regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Regresar.setBorderPainted(false);
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        loguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/mx/interfaces/imagenes/loguito.png"))); // NOI18N

        lbl_Usuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_Usuario.setText("Vendedor de taquilla");

        lbl_listaAsientosSeleccionados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmb_Asiento.setBackground(java.awt.SystemColor.control);
        cmb_Asiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_Asiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Asiento.setBorder(null);
        cmb_Asiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_AsientoItemStateChanged(evt);
            }
        });

        jp_DatosFuncion.setBackground(new java.awt.Color(57, 105, 138));
        jp_DatosFuncion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TituloPelicula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbl_TituloPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TituloPelicula.setText("Título");

        lbl_DescripcionPelicula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_DescripcionPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DescripcionPelicula.setText("Descripción");
        lbl_DescripcionPelicula.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbl_ClasificacionPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_ClasificacionPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ClasificacionPelicula.setText("Clasificación");

        lbl_SalaPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_SalaPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SalaPelicula.setText("Sala");

        lbl_DiaPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_DiaPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DiaPelicula.setText("Día");

        lbl_FormatoPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_FormatoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_FormatoPelicula.setText("Formato");

        lbl_HoraPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_HoraPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_HoraPelicula.setText("Hora");

        lbl_DuracionPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_DuracionPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DuracionPelicula.setText("Duración");

        lbl_CostoPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_CostoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CostoPelicula.setText("Costo");

        javax.swing.GroupLayout jp_DatosFuncionLayout = new javax.swing.GroupLayout(jp_DatosFuncion);
        jp_DatosFuncion.setLayout(jp_DatosFuncionLayout);
        jp_DatosFuncionLayout.setHorizontalGroup(
            jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                        .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_DescripcionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbl_TituloPelicula))
                            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_ClasificacionPelicula)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Portada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                                .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                                        .addComponent(lbl_SalaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_DiaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_HoraPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                                        .addComponent(lbl_DuracionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_FormatoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_CostoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jp_DatosFuncionLayout.setVerticalGroup(
            jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Portada, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TituloPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_DescripcionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ClasificacionPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SalaPelicula)
                    .addComponent(lbl_DiaPelicula)
                    .addComponent(lbl_HoraPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DuracionPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_FormatoPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_CostoPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lbl_Titulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_Titulo.setText("DATOS DE LA VENTA");

        lbl_NombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NombreCliente.setText("Nombre:");

        cmb_TipoPago.setBackground(java.awt.SystemColor.control);
        cmb_TipoPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_TipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_TipoPago.setToolTipText("");
        cmb_TipoPago.setBorder(null);

        lbl_Asiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Asiento.setText("Seleccionar Asientos:");

        lbl_Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Cantidad.setText("Asientos:");

        lbl_SeleccionarFuncion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_SeleccionarFuncion.setText("Seleccionar función:");

        txt_UsuarioCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_UsuarioCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_UsuarioCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_UsuarioCliente.setText("Usuario del cliente:");

        txt_NombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NombreCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_CambioPuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_CambioPuntos.setText("Puntos añadidos:");

        cmb_Función.setBackground(java.awt.SystemColor.control);
        cmb_Función.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_Función.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Función.setToolTipText("");
        cmb_Función.setBorder(null);
        cmb_Función.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_FunciónItemStateChanged(evt);
            }
        });

        lbl_TotalT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TotalT.setText("TOTAL:");

        lbl_Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_TipoPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TipoPago.setText("Tipo de pago:");

        cmb_Descuento.setBackground(java.awt.SystemColor.control);
        cmb_Descuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_Descuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Descuento.setToolTipText("");
        cmb_Descuento.setBorder(null);
        cmb_Descuento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_DescuentoItemStateChanged(evt);
            }
        });

        lbl_Descuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Descuento.setText("Descuento:");

        lbl_Variables.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        sp_Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sp_Cantidad.setBorder(null);
        sp_Cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sp_CantidadStateChanged(evt);
            }
        });
        sp_Cantidad.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                sp_CantidadCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                sp_CantidadInputMethodTextChanged(evt);
            }
        });

        lbl_Subtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_SubtotalT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_SubtotalT.setText("Subtotal:");

        btn_CompletarVenta.setBackground(new java.awt.Color(57, 105, 138));
        btn_CompletarVenta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_CompletarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btn_CompletarVenta.setText("Completar venta");
        btn_CompletarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CompletarVenta.setBorderPainted(false);
        btn_CompletarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CompletarVentaActionPerformed(evt);
            }
        });

        btn_SeleccionarAsientos.setBackground(new java.awt.Color(57, 105, 138));
        btn_SeleccionarAsientos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_SeleccionarAsientos.setForeground(new java.awt.Color(255, 255, 255));
        btn_SeleccionarAsientos.setText("Seleccionar");
        btn_SeleccionarAsientos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_SeleccionarAsientos.setBorderPainted(false);
        btn_SeleccionarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarAsientosActionPerformed(evt);
            }
        });

        btn_SeleccionarAsientos1.setBackground(new java.awt.Color(57, 105, 138));
        btn_SeleccionarAsientos1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_SeleccionarAsientos1.setForeground(new java.awt.Color(255, 255, 255));
        btn_SeleccionarAsientos1.setText("Buscar");
        btn_SeleccionarAsientos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_SeleccionarAsientos1.setBorderPainted(false);
        btn_SeleccionarAsientos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SeleccionarAsientos1ActionPerformed(evt);
            }
        });

        lbl_Actuales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Actuales.setText("Puntos actuales:");

        lbl_PuntosActuales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_PuntosActuales.setText("total");

        javax.swing.GroupLayout jp_PrincipalLayout = new javax.swing.GroupLayout(jp_Principal);
        jp_Principal.setLayout(jp_PrincipalLayout);
        jp_PrincipalLayout.setHorizontalGroup(
            jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_Usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loguito)
                        .addGap(15, 15, 15))))
            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(lbl_PuntosActuales, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_TotalT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3))
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addComponent(lbl_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_PrincipalLayout.createSequentialGroup()
                                        .addComponent(lbl_CambioPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Variables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(2, 2, 2))
                            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                                        .addComponent(lbl_Cantidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sp_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_SeleccionarAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(lbl_SubtotalT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_Subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addComponent(lbl_listaAsientosSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(170, 170, 170))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lbl_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_Actuales, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_SeleccionarFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmb_Función, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmb_Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_UsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                                .addComponent(txt_UsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_SeleccionarAsientos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addGap(10, 10, 10))
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lbl_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jp_DatosFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CompletarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jp_PrincipalLayout.setVerticalGroup(
            jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(loguito)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Usuario)
                        .addGap(40, 40, 40)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jp_DatosFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SeleccionarFuncion)
                            .addComponent(cmb_Función, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cantidad)
                            .addComponent(sp_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Subtotal)
                            .addComponent(lbl_SubtotalT)
                            .addComponent(btn_SeleccionarAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Asiento)
                            .addComponent(cmb_Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_listaAsientosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_UsuarioCliente)
                            .addComponent(txt_UsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SeleccionarAsientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NombreCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Descuento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_Actuales)
                                .addComponent(lbl_PuntosActuales))
                            .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_TotalT)
                                .addComponent(lbl_Total)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TipoPago)
                            .addComponent(cmb_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_CambioPuntos)
                            .addComponent(lbl_Variables, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CompletarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
       this.dispose();
       InicioVentaBoletos inicioVentaBoletos = new InicioVentaBoletos();
       inicioVentaBoletos.setVisible(true);
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void cmb_FunciónItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_FunciónItemStateChanged
        // TODO add your handling code here:
        if(cmb_Función.getSelectedIndex() > 0) {
            int id = cmb_Función.getSelectedIndex() - 1;
            función = InicioSesión.cine.getCartelera().getListaFunciones().get(id);
            Película p = InicioSesión.cine.getCartelera().getListaPelículas().get(función.getId_película());
            lbl_TituloPelicula.setText(p.getNombre());
            lbl_DescripcionPelicula.setText("<html>" + p.getDescripción() + "</html>");
            lbl_ClasificacionPelicula.setText(p.getClasificación());
            lbl_SalaPelicula.setText("Sala " + función.getSala().getID());
            lbl_DiaPelicula.setText(función.getFecha().toString());
            lbl_HoraPelicula.setText(función.getHorario().toString());
            lbl_DuracionPelicula.setText(p.getDuración() + "min");
            lbl_FormatoPelicula.setText(InicioSesión.cine.getCartelera().formato(función.getFormato()));
            lbl_CostoPelicula.setText(Float.toString(función.getCostoBoleto()));
            lbl_Portada.setIcon(new javax.swing.ImageIcon(getClass().getResource(p.getPortada())));
        }
    }//GEN-LAST:event_cmb_FunciónItemStateChanged

    private void sp_CantidadCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sp_CantidadCaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sp_CantidadCaretPositionChanged

    private void sp_CantidadInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_sp_CantidadInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sp_CantidadInputMethodTextChanged

    private void sp_CantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sp_CantidadStateChanged

    }//GEN-LAST:event_sp_CantidadStateChanged

    private void btn_SeleccionarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarAsientosActionPerformed
        int sel = (Integer)sp_Cantidad.getValue();
        if(sel < 1 || cmb_Función.getSelectedIndex() < 1) {
            cmb_Asiento.removeAllItems();
            lbl_Subtotal.setText("");
        } else {
            llenarAsientos();
            total = sel * función.getCostoBoleto();
            lbl_Subtotal.setText(Float.toString(total));
            puntosAñadidos = 5 * sel;
            lbl_Variables.setText(Integer.toString(puntosAñadidos));
            sp_Cantidad.setEnabled(false);
            cmb_Función.setEnabled(false);
        }
    }//GEN-LAST:event_btn_SeleccionarAsientosActionPerformed

    private void cmb_AsientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_AsientoItemStateChanged
        if((Integer)sp_Cantidad.getValue() == 0){
            cmb_Asiento.removeAllItems();
        } else if(cmb_Asiento.getSelectedIndex() > 0) {
            String s = (String)cmb_Asiento.getSelectedItem();
            StringTokenizer st = new StringTokenizer(s, "-");
            st.nextToken();
            int id = Integer.parseInt(st.nextToken()) - 1;
            función.getSala().seleccionarAsiento(id);
            String act = lbl_listaAsientosSeleccionados.getText();
            if("".equals(act)) {
                lbl_listaAsientosSeleccionados.setText(s);
            } else {
                lbl_listaAsientosSeleccionados.setText(act + ", " + s);
            }
            listaBoleto.add(new Boleto(listaBoleto.size(), función.getSala().getID(), id));
            int valor = (Integer)sp_Cantidad.getValue() - 1;
            sp_Cantidad.setValue(valor);
            llenarAsientos();
        }
    }//GEN-LAST:event_cmb_AsientoItemStateChanged

    private void btn_SeleccionarAsientos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SeleccionarAsientos1ActionPerformed
        // TODO add your handling code here:
        String user = txt_UsuarioCliente.getText();
        int i = InicioSesión.cine.getSistemaUsuarios().buscarIDUsuario(user);
        cliente = InicioSesión.cine.getSistemaUsuarios().buscarCliente(new Usuario(i, "", ""));
        if(cliente != null) {
            txt_NombreCliente.setText(cliente.getNombre());
            lbl_PuntosActuales.setText(Integer.toString(cliente.getPuntos()));
        }
    }//GEN-LAST:event_btn_SeleccionarAsientos1ActionPerformed

    private void cmb_DescuentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_DescuentoItemStateChanged
        // TODO add your handling code here:
        if(cmb_Descuento.getSelectedIndex() > 0 && f == false) {
            if(cmb_Descuento.getSelectedIndex() == 1) {
                total -= (float)cliente.getPuntos();
                if(total >= 0) {
                    cliente.setPuntos(0);
                } else {
                    cliente.setPuntos((int) -total);
                    total = 0;
                }
            }
            lbl_PuntosActuales.setText(Integer.toString(cliente.getPuntos()));
            lbl_Total.setText(Float.toString(total));
            f = true;
        }
    }//GEN-LAST:event_cmb_DescuentoItemStateChanged

    private void btn_CompletarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CompletarVentaActionPerformed
        // TODO add your handling code here:
        if(cmb_TipoPago.getSelectedIndex() == 1) {
            try {
                puntosAñadidos += cliente.getPuntos();
                cliente.setPuntos(puntosAñadidos);
                InicioSesión.cine.getCartelera().actualizarSala(función);
                InicioSesión.cine.getSistemaUsuarios().actualizarCliente(cliente);
                dlg_MICHísimasGracias.setSize(600, 320);
                dlg_MICHísimasGracias.setLocationRelativeTo(this);
                dlg_MICHísimasGracias.setVisible(true);
                lbl_Username.setText(cliente.getNombre());
                txt_Puntos.setEditable(true);
                txt_Puntos.setCaretColor(Color.white);
                txt_Puntos.setText(Integer.toString(cliente.getPuntos()));
                InicioSesión.cine.getCajaTaquilla().nuevaVenta(0, Float.parseFloat(lbl_Total.getText()), false, listaBoleto);
            } catch (IOException ex) {
                Logger.getLogger(NuevaVentaBoletos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if(cmb_TipoPago.getSelectedIndex() == 2) {
            dlg_PagoTarjeta.setSize(600, 400);
            dlg_PagoTarjeta.setLocationRelativeTo(this);
            dlg_PagoTarjeta.setVisible(true);
            cmb_TipoTarjeta.removeAllItems();
            cmb_TipoTarjeta.addItem("-Seleccionar-");
            cmb_TipoTarjeta.addItem("Débito");
            cmb_TipoTarjeta.addItem("Crédito");
        }
    }//GEN-LAST:event_btn_CompletarVentaActionPerformed

    private void btn_ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ContinuarActionPerformed
            try {
                dlg_PagoTarjeta.dispose();
                puntosAñadidos += cliente.getPuntos();
                cliente.setPuntos(puntosAñadidos);
                InicioSesión.cine.getCartelera().actualizarSala(función);
                InicioSesión.cine.getSistemaUsuarios().actualizarCliente(cliente);
                dlg_MICHísimasGracias.setSize(600, 320);
                dlg_MICHísimasGracias.setLocationRelativeTo(this);
                dlg_MICHísimasGracias.setVisible(true);
                lbl_Username.setText(cliente.getNombre());
                txt_Puntos.setEditable(true);
                txt_Puntos.setCaretColor(Color.white);
                txt_Puntos.setText(Integer.toString(cliente.getPuntos()));
                InicioSesión.cine.getCajaTaquilla().nuevaVenta(0, Float.parseFloat(lbl_Total.getText()), true, listaBoleto);
            } catch (IOException ex) {
                Logger.getLogger(NuevaVentaBoletos.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_ContinuarActionPerformed

    private void btn_Continuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Continuar1ActionPerformed
        // TODO add your handling code here:
        dlg_MICHísimasGracias.dispose();
        this.dispose();
        InicioVentaBoletos ivb = new InicioVentaBoletos();
        ivb.setVisible(true);
    }//GEN-LAST:event_btn_Continuar1ActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
       dlg_PagoTarjeta.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaVentaBoletos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_CompletarVenta;
    private javax.swing.JButton btn_Continuar;
    private javax.swing.JButton btn_Continuar1;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btn_SeleccionarAsientos;
    private javax.swing.JButton btn_SeleccionarAsientos1;
    private javax.swing.JComboBox<String> cmb_Asiento;
    private javax.swing.JComboBox<String> cmb_Descuento;
    private javax.swing.JComboBox<String> cmb_Función;
    private javax.swing.JComboBox<String> cmb_TipoPago;
    private javax.swing.JComboBox<String> cmb_TipoTarjeta;
    private javax.swing.JDialog dlg_MICHísimasGracias;
    private javax.swing.JDialog dlg_PagoTarjeta;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp_DatosFuncion;
    private javax.swing.JPanel jp_PagoTarjeta;
    private javax.swing.JPanel jp_PagoTarjeta1;
    private javax.swing.JPanel jp_Principal;
    private javax.swing.JLabel lbl_Actuales;
    private javax.swing.JLabel lbl_Asiento;
    private javax.swing.JLabel lbl_CambioPuntos;
    private javax.swing.JLabel lbl_Cantidad;
    private javax.swing.JLabel lbl_ClasificacionPelicula;
    private javax.swing.JLabel lbl_CostoPelicula;
    private javax.swing.JLabel lbl_DatosTarjeta;
    private javax.swing.JLabel lbl_DescripcionPelicula;
    private javax.swing.JLabel lbl_Descuento;
    private javax.swing.JLabel lbl_DiaPelicula;
    private javax.swing.JLabel lbl_DuracionPelicula;
    private javax.swing.JLabel lbl_FormatoPelicula;
    private javax.swing.JLabel lbl_HoraPelicula;
    private javax.swing.JLabel lbl_NombreCliente;
    private javax.swing.JLabel lbl_NombreCompleto;
    private javax.swing.JLabel lbl_NumTarjeta;
    private javax.swing.JLabel lbl_NumTarjeta1;
    private javax.swing.JLabel lbl_PagoTarjeta;
    private javax.swing.JLabel lbl_PagoTarjeta1;
    private javax.swing.JLabel lbl_Portada;
    private javax.swing.JLabel lbl_PuntosActuales;
    private javax.swing.JLabel lbl_SalaPelicula;
    private javax.swing.JLabel lbl_SeleccionarFuncion;
    private javax.swing.JLabel lbl_Subtotal;
    private javax.swing.JLabel lbl_SubtotalT;
    private javax.swing.JLabel lbl_TipoPago;
    private javax.swing.JLabel lbl_TipoTarjeta;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_TituloPelicula;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JLabel lbl_TotalT;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JLabel lbl_UsuarioCliente;
    private javax.swing.JLabel lbl_Variables;
    private javax.swing.JLabel lbl_listaAsientosSeleccionados;
    private javax.swing.JLabel loguito;
    private javax.swing.JSpinner sp_Cantidad;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_NombreCompleto;
    private javax.swing.JTextField txt_NumTarjeta;
    private javax.swing.JTextField txt_Puntos;
    private javax.swing.JTextField txt_UsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
