/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uam.mx.interfaces;

/**
 *
 * @author Laura
 */
public class NuevaVentaBoletos extends javax.swing.JFrame {

    /**
     * Creates new form NuevaVentaBoletos
     */
    public NuevaVentaBoletos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_PagoTarjeta = new javax.swing.JDialog();
        jp_PagoTarjeta = new javax.swing.JPanel();
        lbl_PagoTarjeta = new javax.swing.JLabel();
        txt_NombreCompleto = new javax.swing.JTextField();
        lbl_TipoTarjeta = new javax.swing.JLabel();
        cmb_TipoTarjeta = new javax.swing.JComboBox<>();
        lbl_NumTarjeta = new javax.swing.JLabel();
        lbl_DatosTarjeta = new javax.swing.JLabel();
        lbl_NombreCompleto = new javax.swing.JLabel();
        txt_NumTarjeta = new javax.swing.JTextField();
        btn_Continuar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jp_Principal = new javax.swing.JPanel();
        btn_Regresar = new javax.swing.JButton();
        loguito = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_listaAsientosSeleccionados = new javax.swing.JLabel();
        cmb_Asiento = new javax.swing.JComboBox<>();
        jp_DatosFuncion = new javax.swing.JPanel();
        lbl_Portada = new javax.swing.JLabel();
        lbl_TituloPelicula = new javax.swing.JLabel();
        lbl_DescripcionPelicula = new javax.swing.JLabel();
        lbl_ClasificacionPelicula = new javax.swing.JLabel();
        lbl_SalaPelicula = new javax.swing.JLabel();
        lbl_HoraPelicula = new javax.swing.JLabel();
        lbl_CostoPelicula = new javax.swing.JLabel();
        lbl_nombreCliente = new javax.swing.JLabel();
        lbl_listaAsientosSeleccionados2 = new javax.swing.JLabel();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_NombreCliente = new javax.swing.JLabel();
        cmb_TipoPago = new javax.swing.JComboBox<>();
        lbl_Asiento = new javax.swing.JLabel();
        lbl_Cantidad = new javax.swing.JLabel();
        lbl_SeleccionarFuncion = new javax.swing.JLabel();
        txt_UsuarioCliente = new javax.swing.JTextField();
        lbl_UsuarioCliente = new javax.swing.JLabel();
        txt_NombreCliente = new javax.swing.JTextField();
        lbl_costoBoleto = new javax.swing.JLabel();
        lbl_Costo = new javax.swing.JLabel();
        lbl_CambioPuntos = new javax.swing.JLabel();
        cmb_Funcion = new javax.swing.JComboBox<>();
        lbl_TotalT = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        lbl_TipoPago = new javax.swing.JLabel();
        cmb_Descuento = new javax.swing.JComboBox<>();
        lbl_Descuento = new javax.swing.JLabel();
        lbl_Variables = new javax.swing.JLabel();
        sp_Cantidad = new javax.swing.JSpinner();
        lbl_Subtotal = new javax.swing.JLabel();
        lbl_SubtotalT = new javax.swing.JLabel();
        btn_CompletarVenta = new javax.swing.JButton();

        jp_PagoTarjeta.setBackground(new java.awt.Color(255, 255, 255));

        lbl_PagoTarjeta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_PagoTarjeta.setText("PAGO CON TARJETA");

        txt_NombreCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NombreCompleto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_TipoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TipoTarjeta.setText("Tipo de tarjeta:");

        cmb_TipoTarjeta.setBackground(java.awt.SystemColor.control);
        cmb_TipoTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_TipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_TipoTarjeta.setToolTipText("");
        cmb_TipoTarjeta.setBorder(null);

        lbl_NumTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NumTarjeta.setText("Número de la tarjeta:");

        lbl_DatosTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_DatosTarjeta.setText("Datos de la tarjeta:");

        lbl_NombreCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NombreCompleto.setText("Nombre completo:");

        txt_NumTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NumTarjeta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btn_Continuar.setBackground(new java.awt.Color(57, 105, 138));
        btn_Continuar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_Continuar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Continuar.setText("Continuar");
        btn_Continuar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Continuar.setBorderPainted(false);

        btn_Cancelar.setBackground(new java.awt.Color(102, 102, 102));
        btn_Cancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Cancelar.setBorderPainted(false);

        javax.swing.GroupLayout jp_PagoTarjetaLayout = new javax.swing.GroupLayout(jp_PagoTarjeta);
        jp_PagoTarjeta.setLayout(jp_PagoTarjetaLayout);
        jp_PagoTarjetaLayout.setHorizontalGroup(
            jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PagoTarjetaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_PagoTarjeta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                            .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_NumTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_NombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_NombreCompleto)
                                .addComponent(txt_NumTarjeta)))
                        .addComponent(lbl_DatosTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                            .addComponent(lbl_TipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(cmb_TipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jp_PagoTarjetaLayout.setVerticalGroup(
            jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PagoTarjetaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbl_PagoTarjeta)
                .addGap(31, 31, 31)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TipoTarjeta)
                    .addComponent(cmb_TipoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_DatosTarjeta)
                .addGap(18, 18, 18)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NombreCompleto))
                .addGap(18, 18, 18)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NumTarjeta)
                    .addComponent(txt_NumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jp_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlg_PagoTarjetaLayout = new javax.swing.GroupLayout(dlg_PagoTarjeta.getContentPane());
        dlg_PagoTarjeta.getContentPane().setLayout(dlg_PagoTarjetaLayout);
        dlg_PagoTarjetaLayout.setHorizontalGroup(
            dlg_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_PagoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlg_PagoTarjetaLayout.setVerticalGroup(
            dlg_PagoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_PagoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_Principal.setBackground(new java.awt.Color(255, 255, 255));

        btn_Regresar.setBackground(new java.awt.Color(102, 102, 102));
        btn_Regresar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_Regresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Regresar.setText("Regresar");
        btn_Regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Regresar.setBorderPainted(false);

        loguito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uam/mx/interfaces/imágenes/loguito.png"))); // NOI18N

        lbl_Usuario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_Usuario.setText("Vendedor de taquilla");

        lbl_listaAsientosSeleccionados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_listaAsientosSeleccionados.setText("listaAsientosSeleccionados");

        cmb_Asiento.setBackground(java.awt.SystemColor.control);
        cmb_Asiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_Asiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Asiento.setBorder(null);

        jp_DatosFuncion.setBackground(new java.awt.Color(57, 105, 138));
        jp_DatosFuncion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_TituloPelicula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lbl_TituloPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TituloPelicula.setText("Título");

        lbl_DescripcionPelicula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_DescripcionPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_DescripcionPelicula.setText("Descripción");
        lbl_DescripcionPelicula.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lbl_ClasificacionPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_ClasificacionPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ClasificacionPelicula.setText("Clasificación");

        lbl_SalaPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_SalaPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_SalaPelicula.setText("Sala");

        lbl_HoraPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_HoraPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_HoraPelicula.setText("Hora");

        lbl_CostoPelicula.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_CostoPelicula.setForeground(new java.awt.Color(255, 255, 255));
        lbl_CostoPelicula.setText("Costo");

        lbl_nombreCliente.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombreCliente.setText("nombreCliente");

        lbl_listaAsientosSeleccionados2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lbl_listaAsientosSeleccionados2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_listaAsientosSeleccionados2.setText("listaAsientosSeleccionados");

        javax.swing.GroupLayout jp_DatosFuncionLayout = new javax.swing.GroupLayout(jp_DatosFuncion);
        jp_DatosFuncion.setLayout(jp_DatosFuncionLayout);
        jp_DatosFuncionLayout.setHorizontalGroup(
            jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_DatosFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Portada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_DescripcionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_TituloPelicula))
                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_ClasificacionPelicula))
                    .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                                .addComponent(lbl_SalaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_HoraPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_CostoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_nombreCliente))))
                .addContainerGap())
            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_listaAsientosSeleccionados2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_DatosFuncionLayout.setVerticalGroup(
            jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_DatosFuncionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Portada, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TituloPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_DescripcionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ClasificacionPelicula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_DatosFuncionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SalaPelicula)
                    .addComponent(lbl_HoraPelicula)
                    .addComponent(lbl_CostoPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_listaAsientosSeleccionados2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_Titulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lbl_Titulo.setText("DATOS DE LA VENTA");

        lbl_NombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NombreCliente.setText("Nombre:");

        cmb_TipoPago.setBackground(java.awt.SystemColor.control);
        cmb_TipoPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_TipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_TipoPago.setToolTipText("");
        cmb_TipoPago.setBorder(null);

        lbl_Asiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Asiento.setText("Asiento(s):");

        lbl_Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Cantidad.setText("Cantidad:");

        lbl_SeleccionarFuncion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_SeleccionarFuncion.setText("Seleccionar función:");

        txt_UsuarioCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_UsuarioCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_UsuarioCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_UsuarioCliente.setText("Usuario del cliente:");

        txt_NombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_NombreCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_costoBoleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_costoBoleto.setText("costoBoleto");

        lbl_Costo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Costo.setText("Costo:");

        lbl_CambioPuntos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_CambioPuntos.setText("Cambio/Puntos:");

        cmb_Funcion.setBackground(java.awt.SystemColor.control);
        cmb_Funcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_Funcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Funcion.setToolTipText("");
        cmb_Funcion.setBorder(null);

        lbl_TotalT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TotalT.setText("TOTAL:");

        lbl_Total.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Total.setText("total");

        lbl_TipoPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TipoPago.setText("Tipo de pago:");

        cmb_Descuento.setBackground(java.awt.SystemColor.control);
        cmb_Descuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmb_Descuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_Descuento.setToolTipText("");
        cmb_Descuento.setBorder(null);

        lbl_Descuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Descuento.setText("Descuento:");

        lbl_Variables.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Variables.setText("cambio/puntos");

        sp_Cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sp_Cantidad.setBorder(null);

        lbl_Subtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Subtotal.setText("subtotal");

        lbl_SubtotalT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_SubtotalT.setText("Subtotal:");

        btn_CompletarVenta.setBackground(new java.awt.Color(57, 105, 138));
        btn_CompletarVenta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_CompletarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btn_CompletarVenta.setText("Completar venta");
        btn_CompletarVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CompletarVenta.setBorderPainted(false);

        javax.swing.GroupLayout jp_PrincipalLayout = new javax.swing.GroupLayout(jp_Principal);
        jp_Principal.setLayout(jp_PrincipalLayout);
        jp_PrincipalLayout.setHorizontalGroup(
            jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_Usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loguito)
                        .addGap(15, 15, 15))))
            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                .addGap(0, 31, Short.MAX_VALUE)
                                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                            .addComponent(lbl_Cantidad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sp_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_Costo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_costoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbl_SubtotalT)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_Subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_PrincipalLayout.createSequentialGroup()
                                            .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbl_Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_SeleccionarFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmb_Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmb_Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lbl_listaAsientosSeleccionados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_PrincipalLayout.createSequentialGroup()
                                            .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbl_UsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_UsuarioCliente))))
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addComponent(lbl_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_Variables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                                .addComponent(lbl_TotalT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3))
                                            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                                                .addComponent(lbl_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmb_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lbl_CambioPuntos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(2, 2, 2)))
                        .addGap(10, 10, 10))
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lbl_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jp_DatosFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_CompletarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jp_PrincipalLayout.setVerticalGroup(
            jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_PrincipalLayout.createSequentialGroup()
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(loguito)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Usuario)
                        .addGap(41, 41, 41)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jp_DatosFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_PrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_SeleccionarFuncion)
                            .addComponent(cmb_Funcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cantidad)
                            .addComponent(sp_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Costo)
                            .addComponent(lbl_costoBoleto)
                            .addComponent(lbl_Subtotal)
                            .addComponent(lbl_SubtotalT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Asiento)
                            .addComponent(cmb_Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_listaAsientosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_UsuarioCliente)
                            .addComponent(txt_UsuarioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NombreCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Descuento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TotalT)
                            .addComponent(lbl_Total))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TipoPago)
                            .addComponent(cmb_TipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CambioPuntos)
                            .addComponent(lbl_Variables))))
                .addGap(18, 18, 18)
                .addGroup(jp_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CompletarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaVentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaVentaBoletos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_CompletarVenta;
    private javax.swing.JButton btn_Continuar;
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JComboBox<String> cmb_Asiento;
    private javax.swing.JComboBox<String> cmb_Descuento;
    private javax.swing.JComboBox<String> cmb_Funcion;
    private javax.swing.JComboBox<String> cmb_TipoPago;
    private javax.swing.JComboBox<String> cmb_TipoTarjeta;
    private javax.swing.JDialog dlg_PagoTarjeta;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jp_DatosFuncion;
    private javax.swing.JPanel jp_PagoTarjeta;
    private javax.swing.JPanel jp_Principal;
    private javax.swing.JLabel lbl_Asiento;
    private javax.swing.JLabel lbl_CambioPuntos;
    private javax.swing.JLabel lbl_Cantidad;
    private javax.swing.JLabel lbl_ClasificacionPelicula;
    private javax.swing.JLabel lbl_Costo;
    private javax.swing.JLabel lbl_CostoPelicula;
    private javax.swing.JLabel lbl_DatosTarjeta;
    private javax.swing.JLabel lbl_DescripcionPelicula;
    private javax.swing.JLabel lbl_Descuento;
    private javax.swing.JLabel lbl_HoraPelicula;
    private javax.swing.JLabel lbl_NombreCliente;
    private javax.swing.JLabel lbl_NombreCompleto;
    private javax.swing.JLabel lbl_NumTarjeta;
    private javax.swing.JLabel lbl_PagoTarjeta;
    private javax.swing.JLabel lbl_Portada;
    private javax.swing.JLabel lbl_SalaPelicula;
    private javax.swing.JLabel lbl_SeleccionarFuncion;
    private javax.swing.JLabel lbl_Subtotal;
    private javax.swing.JLabel lbl_SubtotalT;
    private javax.swing.JLabel lbl_TipoPago;
    private javax.swing.JLabel lbl_TipoTarjeta;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_TituloPelicula;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JLabel lbl_TotalT;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JLabel lbl_UsuarioCliente;
    private javax.swing.JLabel lbl_Variables;
    private javax.swing.JLabel lbl_costoBoleto;
    private javax.swing.JLabel lbl_listaAsientosSeleccionados;
    private javax.swing.JLabel lbl_listaAsientosSeleccionados2;
    private javax.swing.JLabel lbl_nombreCliente;
    private javax.swing.JLabel loguito;
    private javax.swing.JSpinner sp_Cantidad;
    private javax.swing.JTextField txt_NombreCliente;
    private javax.swing.JTextField txt_NombreCompleto;
    private javax.swing.JTextField txt_NumTarjeta;
    private javax.swing.JTextField txt_UsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
